In [1]:
import numpy as np
print(np.sqrt(10))

3.1622776601683795


In [2]:
x = [3,5,7,1,2]
print("minimum",np.amin(x))

minimum 1


In [3]:
print("maximum",np.amax(x))

maximum 7


#rounding off

In [4]:
print(np.ceil(34.86))

35.0


In [5]:
y =[5,10,15]
print(np.ceil(np.sum(np.sqrt(y))))


10.0


In [6]:
#declaring an array
xyz = np.array([5,8,13])
print(xyz)

[ 5  8 13]


In [7]:
print(type(xyz))

<class 'numpy.ndarray'>


In [8]:
xyz.dtype

dtype('int32')

In [9]:
b = np.asarray(xyz)

In [10]:
b

array([ 5,  8, 13])

In [11]:
print(b)

[ 5  8 13]


In [12]:
#datatype
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("matrix\n", mat)

matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(type(mat))

<class 'numpy.ndarray'>


In [14]:
print(mat.ndim)

2


In [15]:
#total no of elements in matrix


In [16]:
print(mat.size)

9


In [17]:
#number of element across each axis
print(mat.shape)

(3, 3)


In [18]:
print(mat.dtype)

int32


arrange and line space

In [19]:
a = np.arange(2,10.5,4)#runs with numpy range(because of float)
a

array([ 2.,  6., 10.])

In [20]:
print(list(range(2,1)))# don't run with python range

[]


In [21]:
print(a[::-1])#revrse order

[10.  6.  2.]


In [22]:
b =np.linspace(10,40,5, endpoint = False, retstep = True) # 10 or 40 ke beech mein 5
print(b)

(array([10., 16., 22., 28., 34.]), 6.0)


genrate random function

In [23]:
np.random.seed(6)
print(np.random.rand(10,6))

[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [24]:
print(np.random.randn(10,3))

[[-0.37550472  0.39636757 -0.47144628]
 [ 2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539]
 [-0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842]
 [-1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739]
 [ 1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977]
 [-0.09084699  0.17629034  1.09462041]]


In [25]:
print(np.random.randint(5,200,100))# seed will not work

[100  76 138  77  84  44 104 175  10  62 104 125 101  28 129  92  50 164
 149  40   7 104  19  25 130  34 190 133 107 195 104  23 102  93 165  76
 149 118 109  42  51  94 177 189 178 170  65 134 113 198 119  30  30 170
  21  73 187 199  17  54  52  19 129  99 159  69  96 135   7  69  44  16
  91  43 175 149  14 154  34 196 191  29 199  25  39 104  46  67  41  68
 196 181 132 138  31 172 102  38  43  63]


program to genrate the otp

otp = (np.random.randint(1000, 10000))
print(otp)

flag = 0
while (flag==0):
    
    otpin = int(input("Enter your otp"))
    if otpin == otp:
        print("your otp is correct :",otp)
        flag =1
        
    else:
        print("invalid otp")

# numpy conditions

In [26]:
from numpy.random import randint as ri
aa = ri(1,99,30)
print(aa)  


[25 34 70 42 93 14 30  3 83 12 85 59 40 34 22 68 53 32 69 22  7  9 54 30
 24 60 97  4 53 61]


In [27]:
c = aa.reshape(6,5)
c

array([[25, 34, 70, 42, 93],
       [14, 30,  3, 83, 12],
       [85, 59, 40, 34, 22],
       [68, 53, 32, 69, 22],
       [ 7,  9, 54, 30, 24],
       [60, 97,  4, 53, 61]])

In [28]:
print(c.min())

3


In [29]:
print(c.max())

97


In [30]:
import numpy as np
m = ri(1,100,25).reshape(5,5)
print(np.sort(m))#default axis =1 sorted matrix along eachother

[[ 1  8 23 35 48]
 [25 30 41 47 79]
 [ 6 25 59 71 98]
 [ 2 12 12 43 45]
 [ 8  8 64 70 97]]


In [31]:
emp_salary = ri(8000,70000,10)
print(emp_salary)

[35781 64712 16109 63114 28483 45796 61415 47785 32258 64570]


In [32]:
print(emp_salary[np.where(emp_salary<25000)])

[16109]


In [33]:
print(np.where(emp_salary<25000))

(array([2], dtype=int64),)


In [34]:
np.clip(emp_salary,a_min = 20000,a_max=50000)

array([35781, 50000, 20000, 50000, 28483, 45796, 50000, 47785, 32258,
       50000])